//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektManager
{
    using System;
    using System.Collections.Generic;
    
    enum CegTipus
    {
        Magánszemély,
        Cég
    }
    public partial class Cegek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cegek()
        {
            this.ceg_alkalmazottak = new HashSet<ceg_alkalmazottak>();
            this.projektek = new HashSet<Projektek>();
        }
    
        public int id { get; set; }
        public Nullable<int> adoszam { get; set; }
        public string orszag { get; set; }
        public string iranyitoszam { get; set; }
        public string telepules { get; set; }
        public string kozterulet { get; set; }
        public string kozterulet_jellege { get; set; }
        public string hazszam { get; set; }
        public string cegnev { get; set; }
        public string ceg_tipus { get; set; }
        public string telefonszam { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ceg_alkalmazottak> ceg_alkalmazottak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projektek> projektek { get; set; }
    }
}
