//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektDBEntities : DbContext
    {
        public ProjektDBEntities()
            : base("name=ProjektDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alkalmazottak> alkalmazottak { get; set; }
        public virtual DbSet<ceg_alkalmazottak> ceg_alkalmazottak { get; set; }
        public virtual DbSet<cegek> cegek { get; set; }
        public virtual DbSet<projekt_szolgaltatasok> projekt_szolgaltatasok { get; set; }
        public virtual DbSet<projektek> projektek { get; set; }
        public virtual DbSet<statuszok> statuszok { get; set; }
        public virtual DbSet<szolgaltatasok> szolgaltatasok { get; set; }
    }
}
