//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectManagerDBEntities : DbContext
    {
        public ProjectManagerDBEntities()
            : base("name=ProjectManagerDBEntities")
        {
        }
    
        /*protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }*/
    
        public virtual DbSet<Alkalmazottak> alkalmazottak { get; set; }
        public virtual DbSet<ceg_alkalmazottak> ceg_alkalmazottak { get; set; }
        public virtual DbSet<Cegek> cegek { get; set; }
        public virtual DbSet<Projekt_szolgaltatasok> projekt_szolgaltatasok { get; set; }
        public virtual DbSet<Projektek> projektek { get; set; }
        public virtual DbSet<Statuszok> statuszok { get; set; }
        public virtual DbSet<Szolgaltatasok> szolgaltatasok { get; set; }
    }
}
