//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektManager
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using System.Linq.Expressions;

    [Table("projektek")]
    public partial class Projektek : IQueryable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projektek()
        {
            this.projekt_szolgaltatasok = new HashSet<Projekt_szolgaltatasok>();
           
        }
        int id;
        string megnevezes;
        int ceg_id;
      string statusz;
        DateTime hatarido;

        public virtual IQueryable<Projektek> projektek { get; set; }
        public virtual ICollection<Projekt_szolgaltatasok> projekt_szolgaltatasok { get; set; }
        public virtual Cegek cegek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public int Id { get => id; set => id = value; }
        public string Megnevezes { get => megnevezes; set => megnevezes = value; }
        public int Ceg_id { get => ceg_id; set => ceg_id = value; }
        public string Statusz { get => statusz; set => statusz = value; }
        public DateTime Hatarido { get => hatarido; set => hatarido = value; }

        public Expression Expression => throw new NotImplementedException();

        public Type ElementType => throw new NotImplementedException();

        public IQueryProvider Provider => throw new NotImplementedException();

        public Projektek(ICollection<Projekt_szolgaltatasok> projekt_szolgaltatasok, Cegek cegek, int id, string megnevezes, int ceg_id, string statusz, DateTime hatarido)
        {
            this.projekt_szolgaltatasok = projekt_szolgaltatasok;
            this.cegek = cegek;
            Id = id;
            Megnevezes = megnevezes;
            Ceg_id = ceg_id;
            Statusz = statusz;
            Hatarido = hatarido;
        }

        public IEnumerator GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
    
}
