//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekt_szolgaltatasok
    {
        public int id { get; set; }
        public int projekt_id { get; set; }
        public int szolgaltatas_id { get; set; }
        public int statusz_id { get; set; }
        public int egyseg_ar { get; set; }
        public double mennyiseg { get; set; }
        public string megjegyzes { get; set; }
        public string szinkod { get; set; }
    
        public virtual Projektek projektek { get; set; }
        public virtual Statuszok statuszok { get; set; }
        public virtual Szolgaltatasok szolgaltatasok { get; set; }
    }
}
